apiVersion: v1
kind: Service
metadata:
  name: learning-k8s-service
  namespace: learning-k8s

spec:
  selector:
    app: learning-k8s

  type: LoadBalancer

  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080